Add PostalTradeAddressModel
it-kmitl-2018/group10 pull request #10
Opened 2018-03-06 05:53 UTC by amoeba99

2018-03-06 10:45 UTC, champillon requested changes
ทำไมไม่มี test ครับ

2018-03-07 11:44 UTC, amoeba99 commented
เพิ่ม test แล้วครับ

2018-03-08 03:35 UTC, champillon requested changes
ฝากแก้ไขด้วยครับ

2018-03-08 03:35 UTC, champillon commented on Backend/src/test/kotlin/th/ac/kmitl/it/soa/group10/tradeService/PostalAddressModelTest.kt
> +
อันนี้เว้นไว้ทำไมครับ?

2018-03-08 03:35 UTC, champillon commented on Backend/src/test/kotlin/th/ac/kmitl/it/soa/group10/tradeService/PostalAddressModelTest.kt
> +    var postcodeCode = "74000";
ทำไมตั้งชื่อตัวแปรว่า postcodeCode หล่ะครับ codeCode ซ้ำกัน

2018-03-08 03:35 UTC, champillon commented on Backend/src/main/kotlin/th/ac/kmitl/it/soa/group10/model/supplyChainTradeTransaction/PostalTradeAddressModel.kt
> +data class PostalTradeAddressModel(var postcodeCode: String, var cityName: String, var citySubDivisionName: String,
น่าจะตั้งชื่ออะไรให้ง่ายกว่านี้ เช่น Address

2018-03-08 05:06 UTC, amoeba99 commented on Backend/src/test/kotlin/th/ac/kmitl/it/soa/group10/tradeService/PostalAddressModelTest.kt
> +    var postcodeCode = "74000";
โทษทีครับ พอดีเห็นใน XML ใช้ชื่อนี้ จะแก้ไขให้ครับ

2018-03-08 05:06 UTC, amoeba99 commented on Backend/src/main/kotlin/th/ac/kmitl/it/soa/group10/model/supplyChainTradeTransaction/PostalTradeAddressModel.kt
> +data class PostalTradeAddressModel(var postcodeCode: String, var cityName: String, var citySubDivisionName: String,
รับทราบครับ

2018-03-08 06:20 UTC, champillon approved these changes
LGTM la

2018-03-13 03:54 UTC, merged

2018-03-14 08:18 UTC, champillon commented
คะแนนครับ 1 คะแนน
5.1 การ design เป็น components เพื่อทำให้คนอื่นทำงานร่วมกันต่อได้ง่าย => 1 คะแนน
5.2 คุณภาพของการตั้งชื่อตัวแปร, ฟังก์ชั่น และความเรียบร้อยของ code => 0 คะแนน
5.3 ความยากเชิงเทคนิคที่นำมาประยุกต์ใช้ เช่น แปลง XML Schema เป็น Java code => 0 คะแนน
5.4 รายละเอียดการตั้งชื่อใน PR name และ commit log รวมทั้งรายละเอียดที่บรรยายใน issue ของ PR นั้นๆ => 0 คะแนน
5.5 ความสอดคล้องกันกับ PR อื่นๆของทีม ที่ทำงานร่วมกันได้ดี => 0 คะแนน