Init kotlinwith spring boot
it-kmitl-2018/group10 pull request #5
Opened 2018-02-12 15:41 UTC by aliveable

just initializer spring boot

2018-02-14 08:54 UTC, champillon requested changes
ทำไมยังมี *.class อยู่หล่ะครับ เราใช้ gradle เป็น build tool แล้วก็ไม่ควรมีนะครับ

2018-02-14 08:54 UTC, champillon commented on Backend/src/test/kotlin/th/ac/kmitl/it/soa/group10/tradeService/TradeServiceApplicationTests.kt
> +	fun contextLoads() {
อันนี้ไว้ทำอะไรครับ?

2018-02-14 08:54 UTC, champillon commented on CONVENSION.md
> +Code Convention
PR นี้ init project แล้วทำไมมีการแก้ convention มาหล่ะครับ

2018-02-14 09:03 UTC, aliveable commented on CONVENSION.md
> +Code Convention
เพราะ อันที่แก้พี่เมิจลง มาสเตอร์ไปแล้วครับ ตอนแรกมันอยู่คนละ branch กันครับตอนทดลองทำในห้อง อันนั้นแก้แล้ว ถ้าอันนี้เมิจลงมาสเตอร์ เดี๋ยวมันก็เป็นอันล่าสุดเองอะครับ

2018-02-14 09:09 UTC, champillon commented on CONVENSION.md
> +Code Convention
แยกเป็นอีก PR ดีกว่าครับ

2018-02-14 09:10 UTC, aliveable commented on CONVENSION.md
> +Code Convention
หมายถึง แค่ convention หรอครับพี่

2018-02-14 09:24 UTC, champillon commented on CONVENSION.md
> +Code Convention
ใช่ครับ

2018-02-14 09:26 UTC, aliveable commented on CONVENSION.md
> +Code Convention
พี่พึ่งเมิจลงมาสเตอร์ตะกี้นี้เองอะพี่ งั้นเดี๋ยวผมเอาคอนเวนชั่นตัวนี้ออกแทนละกันนะครับ

2018-02-14 09:27 UTC, champillon commented on CONVENSION.md
> +Code Convention
ได้ครับ

2018-02-14 09:48 UTC, keattiwut reviewed
application.properties ลองเปลี่ยนไปใช้ แบบ yaml จะอ่านง่ายกว่านะครับ

2018-02-14 13:45 UTC, keattiwut commented on Backend/out/production/resources/application.properties
> +## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
File ที่อยู่ใน path out ไม่ควร commit ขึ้นมาด้วยนะครับ ให้ไปเพิ่ม exclude ใน .gitignore นะครับ

2018-03-06 03:10 UTC, merged

2018-03-06 09:45 UTC, champillon commented
คะแนนครับ 1.25 คะแนน
5.1 การ design เป็น components เพื่อทำให้คนอื่นทำงานร่วมกันต่อได้ง่าย => 0 คะแนน
5.2 คุณภาพของการตั้งชื่อตัวแปร, ฟังก์ชั่น และความเรียบร้อยของ code => 0.5 ชื่อตัวแปรยังอ่านไม่ค่อยรู้เรื่องเท่าไหร่
5.3 ความยากเชิงเทคนิคที่นำมาประยุกต์ใช้ เช่น แปลง XML Schema เป็น Java code => 0 คะแนน ยังไม่มีอะไรยาก 
5.4 รายละเอียดการตั้งชื่อใน PR name และ commit log รวมทั้งรายละเอียดที่บรรยายใน issue ของ PR นั้นๆ => 0.75 คะแนน (PR บางอันยังไม่สื่อ
5.5 ความสอดคล้องกันกับ PR อื่นๆของทีม ที่ทำงานร่วมกันได้ดี => 0 ยังไม่เห็นการทำงานร่วมกันเพื่อนๆ